package:
  name: responses
  version: "0.5.1"

source:
  fn: responses-0.5.1.tar.gz
  url: https://files.pythonhosted.org/packages/09/e4/ae639e37d9d35903fdeda416d7f9c9e3a0331895d574b4fe6632a27c9190/responses-0.5.1.tar.gz
  md5: f1962b295b18128c522e83901556deac
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - responses = responses:main
    #
    # Would create an entry point called responses that calls responses.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=2.0
    - cookies
    - six
    - mock

  run:
    - python
    - requests >=2.0
    - cookies
    - six
    - mock

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/getsentry/responses
  license: Apache 2.0
  summary: 'A utility library for mocking out the `requests` Python library.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
