package:
  name: celery
  version: !!str 3.1.9

source:
  fn: celery-3.1.9.tar.gz
  url: https://pypi.python.org/packages/source/c/celery/celery-3.1.9.tar.gz
  md5: 5742a95c0bb07cc5159216aae3b025fb
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - celery = celery:main
    #
    # Would create an entry point called celery that calls celery.main()

    - celery = celery.__main__:main
    - celeryd = celery.__main__:_compat_worker
    - celerybeat = celery.__main__:_compat_beat
    - celeryd-multi = celery.__main__:_compat_multi

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pytz
    - billiard >=3.3.0.14,<3.4
    - kombu >=3.0.12,<4.0

  run:
    - python
    - pytz
    - billiard >=3.3.0.14,<3.4
    - kombu >=3.0.12,<4.0
    - sqlalchemy

test:
  imports:
    - celery
    - celery.app
    - celery.apps
    - celery.backends
    - celery.backends.database
    - celery.bin
    - celery.concurrency
    - celery.contrib
    - celery.events
    - celery.fixups
    - celery.loaders
    - celery.security
    - celery.task
    - celery.tests
    - celery.tests.app
    - celery.tests.backends
    - celery.tests.bin
    - celery.tests.bin.proj
    - celery.tests.compat_modules
    - celery.tests.concurrency
    - celery.tests.contrib
    - celery.tests.events
    - celery.tests.fixups
    - celery.tests.functional
    - celery.tests.security
    - celery.tests.slow
    - celery.tests.tasks
    - celery.tests.utils
    - celery.tests.worker
    - celery.utils
    - celery.utils.dispatch
    - celery.worker

about:
  home: http://celeryproject.org
  license: BSD License
  summary: 'Distributed Task Queue'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
