package:
  name: tzwhere
  version: "3.0.1"

source:
  fn: tzwhere-3.0.1.tar.gz
  url: https://pypi.python.org/packages/55/d8/4829945753281b6babbd9726144703d02ab92a03bb7bb26d0bfea099655a/tzwhere-3.0.1.tar.gz
  md5: 3c9ac790c541785b7a16427954c1a683

requirements:
  build:
    - python
    - setuptools
    - shapely

  run:
    - python
    - shapely

test:
  # Python imports
  imports:
    - tzwhere

about:
  home: https://github.com/pegler/pytzwhere
  license: MIT License
  license_file: LICENSE
  summary: 'Python library to look up timezone from lat / long offline'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
