package:
  name: earthengine-api
  version: "0.1.111"

source:
  fn: earthengine-api-0.1.111.tar.gz
  url: https://pypi.python.org/packages/f4/5f/5b709e5acf338014902b8d3f42fd8c624df57473c635d15e6e628cc62d0d/earthengine-api-0.1.111.tar.gz
  md5: 0ff79d1faa873faf4a267f042cdb6acd
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - earthengine-api = earthengine-api:main
    #
    # Would create an entry point called earthengine-api that calls earthengine-api.main()

    - earthengine = ee.cli.eecli:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - google-api-python-client
    - pyopenssl >=0.11

  run:
    - python
    - google-api-python-client
    - pyopenssl >=0.11

test:
  # Python imports
  imports:
    - ee
    - ee.cli

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - earthengine --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://code.google.com/p/earthengine-api/
  license: Apache Software License
  summary: 'Earth Engine Python API'
  license_family: APACHE

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
