package:
  name: natcap.versioner
  version: "0.5.0"

source:
  fn: natcap.versioner-0.5.0.tar.gz
  url: https://pypi.python.org/packages/37/57/665936a6f6b09d41aa798b5e94c9aaf44a197f8aa7404997a22c66275062/natcap.versioner-0.5.0.tar.gz
  md5: 5d567309129c79b4f0e55259ea916f14
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch: python
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - natcap.versioner = natcap.versioner:main
    #
    # Would create an entry point called natcap.versioner that calls natcap.versioner.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - setuptools
    - six

test:
  # Python imports
  imports:
    - natcap
    - natcap.versioner

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/jdouglass/versioner
  license: BSD License
  summary: 'PEP440-compliant Git and hg versioning'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
