package:
  name: python-magic
  version: "0.4.9"

source:
  fn: python-magic-0.4.9.tar.gz
  url: https://pypi.python.org/packages/c7/2a/deb502009b4b0a96c00988346f14e2b698f56928ca48d080e3a6fb8580d0/python-magic-0.4.9.tar.gz
  md5: a0799600d9e227fffbb0cf403722663c
 patches:
   # List any patch files here
   - add_env_path.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-magic = python-magic:main
    #
    # Would create an entry point called python-magic that calls python-magic.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - libmagic

  run:
    - python
    - libmagic

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/ahupp/python-magic
  license: MIT License
  summary: 'File type identification using libmagic'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
