package:
  name: utm
  version: "0.4.0"

source:
  fn: utm-0.4.0.tar.gz
  url: https://pypi.python.org/packages/source/u/utm/utm-0.4.0.tar.gz
  md5: 613a1f0ac10372eff2f313cf24edfe2e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - utm = utm:main
    #
    # Would create an entry point called utm that calls utm.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - utm

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/Turbo87/utm
  license: MIT License
  summary: 'Bidirectional UTM-WGS84 converter for python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
