package:
  name: httpbin
  version: "0.4.1"

source:
  fn: httpbin-0.4.1.tar.gz
  url: https://files.pythonhosted.org/packages/bd/4e/665a7ac9e0c5c2dcec4646507b1cdf276377307d74ec2bf08ee10332cbc8/httpbin-0.4.1.tar.gz
  md5: 5560286d2ea477a7c05877dbc300e46d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - httpbin = httpbin:main
    #
    # Would create an entry point called httpbin that calls httpbin.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - flask
    - markupsafe
    - decorator
    - itsdangerous
    - six

  run:
    - python
    - flask
    - markupsafe
    - decorator
    - itsdangerous
    - six

test:
  # Python imports
  imports:
    - httpbin

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/Runscope/httpbin
  license: MIT License
  summary: 'HTTP Request and Response Service'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
