package:
  name: structlog
  version: "15.3.0"

source:
  fn: structlog-15.3.0.tar.gz
  url: https://pypi.python.org/packages/source/s/structlog/structlog-15.3.0.tar.gz
  md5: 373666bf2cfb5677182e382f7f38e6c2
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - structlog = structlog:main
    #
    # Would create an entry point called structlog that calls structlog.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - structlog

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.structlog.org/
  license: Apache Software License or MIT License
  summary: 'Structured Logging for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
