package:
  name: rpy2
  version: !!str 2.8.0

source:
  fn: rpy2-2.8.0.tar.gz
  url: https://pypi.python.org/packages/c3/ce/dc91e8879b84771fda231b0a1b46e09615bd072d1d2b135b3ee5913b66c3/rpy2-2.8.0.tar.gz
  md5: cfb51aa4429f81b54afd13dca06b9749
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rpy2 = rpy2:main
    #
    # Would create an entry point called rpy2 that calls rpy2.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - singledispatch

  run:
    - python
    - pandas
    - ipython
    - singledispatch

test:
  # Python imports
  imports:
    - rpy2
    # readline fixes the following imports in lucid builds
    - readline
    - rpy2.interactive
    - rpy2.interactive.tests
    - rpy2.ipython
    - rpy2.ipython.tests
    - rpy2.rinterface
    - rpy2.rinterface.tests
    - rpy2.rlike
    - rpy2.rlike.tests
    - rpy2.robjects
    - rpy2.robjects.lib
    - rpy2.robjects.lib.tests
    - rpy2.robjects.tests

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://rpy.sourceforge.net
  license:  GNU General Public License v2 or later (GPLv2+)
  summary: 'Python interface to the R language (embedded R)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
