package:
  name: pytest_httpbin
  version: "0.2.3"

source:
  fn: pytest-httpbin-0.2.3.tar.gz
  url: https://files.pythonhosted.org/packages/12/12/5430600cb9417080b561237761ff2dffde520b664cc352433d2e57051222/pytest-httpbin-0.2.3.tar.gz
  md5: b8ebb8e2fbac1a445fb5d044f7fec556
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pytest_httpbin = pytest_httpbin:main
    #
    # Would create an entry point called pytest_httpbin that calls pytest_httpbin.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - flask
    - decorator
    - httpbin
    - six
    - pytest

  run:
    - python
    - setuptools
    - flask
    - decorator
    - httpbin
    - six
    - pytest

test:
  # Python imports
  imports:
    - pytest_httpbin

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/kevin1024/pytest-httpbin
  license: MIT License
  summary: 'Easily test your HTTP library against a local copy of httpbin'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
