package:
  name: yhat
  version: "1.3.6"

source:
  fn: yhat-1.3.6.tar.gz
  url: https://pypi.python.org/packages/source/y/yhat/yhat-1.3.6.tar.gz
  md5: 011743377a7aa27c5c01adbc77e1ccfe
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - yhat = yhat:main
    #
    # Would create an entry point called yhat that calls yhat.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pip
    - flask ==0.10.1
    - websocket-client ==0.12.0
    - dill ==0.2b1
    - terragon ==0.1.4
    - progressbar ==2.2
    - poster ==0.8.1

  run:
    - python
    - pip
    - flask ==0.10.1
    - websocket-client ==0.12.0
    - dill ==0.2b1
    - terragon ==0.1.4
    - progressbar ==2.2
    - poster ==0.8.1

test:
  # Python imports
  imports:
    - yhat
    - yhat.deployment

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/yhat/yhat-client
  license: BSD
  summary: 'Python client for Yhat (http://yhathq.com/)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
