package:
  name: gdal
  version: 1.11.1

source:
  fn: gdal-1.11.1.tar.gz
  url: http://download.osgeo.org/gdal/1.11.1/gdal-1.11.1.tar.gz
  md5: 7555f55855f613be49e6508eed0ac3fa

requirements:
  build:
    - python
  run:
    - python

test:
  files:
    - os1_hw.py
    - sites.dbf
    - sites.sbn
    - sites.sbx
    - sites.shp
    - sites.shx
  imports:
    - osgeo

about:
  home: http://www.gdal.org/
  license: MIT
