package:
  name: properscoring
  version: "0.1"

source:
  fn: properscoring-0.1.tar.gz
  url: https://pypi.python.org/packages/source/p/properscoring/properscoring-0.1.tar.gz
  md5: f1fe6cc96c24713a28886c2c0b47afd6

build:
  noarch_python: True

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy

  run:
    - python
    - numpy
    - scipy
    - numba

test:
  imports:
    - properscoring

  requires:
    - nose

  commands:
    - nosetests properscoring.tests.test_brier
    - nosetests properscoring.tests.test_crps
    - nosetests properscoring.tests.test_utils

about:
  home: https://github.com/TheClimateCorporation/properscoring
  license: Apache Software License
  summary: 'Proper scoring rules in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
